spring:
  application:
    name: foro
  datasource:
    url: jdbc:postgresql://localhost:5432/challenge
    username: ${DB_USER:postgres}
    password: ${DB_PASS:}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  flyway:
    enabled: true

api:
  security:
    token:
      secret: ${JWT_SECRET:secretkeyforauthenticationtoken12345678}
